#!/bin/sh
# jail-X driver

cmd=help
case "${1}" in
  (list|ls)
    cmd=list
    ;;
  (ifconfig|if|ip)
    cmd=ifconfig
    ;;
  (update|up)
    cmd=update
    ;;
  (version|ver)
    cmd=version
    ;;
  (package|pkg)
    cmd=package
    ;;
  (sync|syn)
    cmd=sync
    ;;
  (console|c)
    shift
    exec jexec -l "${@}"
    ;;
  (start|s)
    shift
    exec service jail onestart "${@}"
    ;;
  (stop|stp)
    shift
    exec service jail onestop "${@}"
    ;;
  (*)
    printf 'invalid command: %s\n' "${1}"
    ;;
esac

if [ X"${cmd}" = X"help" ]
then
  cat <<EOF
supported commands:
  list       (ls)    list running jails
  ifconfig   (ip)    list jail ipaddresses
  update     (up)    update/upgrade a jail
  version    (ver)   list running jail userland version
  package    (pkg)   upgrade packages in a jail
  sync       (syn)   update jl and associated scripts from repository
EOF
  exit 1
fi

shift
exec "jail-${cmd}" "${@}"
