#!/bin/sh
# jail-X driver

cmd=help
case "${1}" in
  (list|ls)
    cmd=list
    ;;
  (ifconfig|if|ip)
    cmd=ifconfig
    ;;
  (update|up)
    cmd=update
    ;;
  (version|ver)
    cmd=version
    ;;
  (package|pkg)
    cmd=package
    ;;
  (sync|syn)
    cmd=sync
    ;;
  (uname|un)
    cmd=uname
    ;;
  (memory|m)
    cmd=memory
    ;;
  (console|c)
    shift
    exec jexec -l "${@}"
    ;;
  (start|s)
    shift
    exec service jail onestart "${@}"
    ;;
  (stop|stp)
    shift
    exec service jail onestop "${@}"
    ;;
  (enable|e)
    shift
    for j in "${@}"
    do
      sysrc -q jail_list+="${j}" > /dev/null
    done
    printf 'enabled: '
    exec sysrc jail_list
    ;;
  (disable|d)
    shift
    for j in "${@}"
    do
      sysrc -q jail_list-="${j}" > /dev/null
    done
    printf 'enabled: '
    exec sysrc jail_list
    ;;

  (*)
    printf 'invalid command: %s\n' "${1}"
    ;;
esac

if [ X"${cmd}" = X"help" ]
then
  cat <<EOF
supported commands:
  list       (ls)    list running jails
  ifconfig   (ip)    list jail ipaddresses
  update     (up)    update/upgrade a jail's userland
  uname      (un)    update a jail's osrelease/osreldate (requires jail restart)
  version    (ver)   list running jail userland version
  package    (pkg)   upgrade packages in a jail
  sync       (syn)   update jl and associated scripts from repository
  memory     (m)     summaris jail processes and memory usage
  console    (c)     open a console into a jail
  start      (s)     start one or more jails
  stop       (stp)   stop one or more jails
  enable     (e)     enable one or more jails to start at boot
  disable    (d)     disable one or more jails from starting at boot
EOF
  exit 1
fi

shift
exec "jail-${cmd}" "${@}"
